from __future__ import annotations

import json

from tooling.workflow_features.onboarding.model import (
    CONFIDENCE_MEANING,
    GREENFIELD,
    BootstrapReport,
)


UNDERIVABLE_FACTS = (
    "Product purpose, when neither a manifest nor the README states it",
    "Primary users and stakeholders",
    "Lifecycle stage: discovery, active development, production, or maintenance",
    "Business capabilities and which boundaries are intentional",
    "Security and privacy constraints",
)

AGENT_PROMPT = """`adopt` has already filled every field the evidence supports. Finish the rest.

1. Run each command in .agent/COMMANDS.md once. Fix or remove any row that fails.
2. For every field in .agent/PROJECT.md still marked TODO, find the answer in this
   repository and cite the file. Anything you cannot ground in a file becomes the literal
   word "unknown" - do not infer purpose or users from code; ask me instead.
3. Correct any adopted value the code contradicts.
4. Do not modify application source code during onboarding."""


def _header(report: BootstrapReport) -> list[str]:
    meanings = "\n".join(f"- `{key}` — {value}" for key, value in CONFIDENCE_MEANING.items())
    return [
        "# Onboarding suggestions",
        "",
        "Generated by `python .agent/workflow.py bootstrap`. Regenerate with `--force`.",
        "",
        "**These are suggestions, not facts.** Bootstrap reads files; it never runs them and never "
        "guesses. `python .agent/workflow.py adopt` writes the suggestions labelled "
        "`ci`, `declared`, `documented`, or `observed` into fields that are still `TODO`, and never "
        "replaces a value someone wrote. `derived` suggestions always wait for a person.",
        "",
        f"- Mode: `{report.mode}`",
        f"- Technology profiles to load: {_profiles(report)}",
        "",
        "Evidence labels:",
        "",
        meanings,
        "",
    ]


def _profiles(report: BootstrapReport) -> str:
    if not report.profiles:
        return "none detected"
    return ", ".join(f"`profiles/{name}.md`" for name in report.profiles)


def _ecosystems(report: BootstrapReport) -> list[str]:
    if not report.ecosystems:
        return ["## Detected ecosystems", "", "None. No package manifest was found.", ""]
    lines = ["## Detected ecosystems", "", "| Ecosystem | Package manager | Evidence |", "|---|---|---|"]
    for item in report.ecosystems:
        manager = item.package_manager or "unknown"
        lines.append(f"| {item.name} | {manager} | `{item.evidence}` |")
    lines.append("")
    return lines


def _commands(report: BootstrapReport) -> list[str]:
    lines = ["## Candidate commands for `.agent/COMMANDS.md`", ""]
    if not report.commands:
        lines.extend(["No command could be derived from any file in this repository.", ""])
        return lines
    lines.extend(
        [
            "`adopt` writes every `ci` and `declared` row into `.agent/COMMANDS.md`; `derived` rows wait for a person.",
            "",
            "| Operation | Command | Evidence | Confidence |",
            "|---|---|---|---|",
        ]
    )
    for item in report.commands:
        lines.append(f"| {item.operation} | `{item.command}` | `{item.evidence}` | {item.confidence} |")
    lines.append("")
    return lines


def _facts(report: BootstrapReport) -> list[str]:
    lines = ["## Project facts for `.agent/PROJECT.md`", ""]
    if not report.facts:
        lines.extend(["No project fact could be read from this repository.", ""])
        return lines
    lines.extend(["| Field | Value | Evidence | Confidence |", "|---|---|---|---|"])
    for item in report.facts:
        lines.append(f"| {item.field} | {item.value} | {item.evidence} | {item.confidence} |")
    lines.append("")
    return lines


def _scopes(report: BootstrapReport) -> list[str]:
    lines = ["## Candidate scopes", ""]
    if not report.scopes:
        lines.extend(["No bounded area was detected. A single-scope repository needs none.", ""])
        return lines
    lines.extend(
        [
            "Declare a scope only for an area you actually route work to. Fewer is better.",
            "",
            "| Scope | Kind | Path | Evidence |",
            "|---|---|---|---|",
        ]
    )
    for item in report.scopes:
        lines.append(f"| `{item.scope_id}` | {item.kind} | `{item.path}` | {item.evidence} |")
    lines.extend(["", "```shell"])
    lines.extend(item.creation_command() for item in report.scopes)
    lines.extend(["```", ""])
    return lines


def _modules(report: BootstrapReport) -> list[str]:
    lines = ["## Candidate architecture modules", ""]
    if not report.modules:
        lines.extend(["No module boundary could be derived.", ""])
        return lines
    rules = {"schema_version": 1, "adapter_mode": "auto", "modules": [item.as_rule() for item in report.modules]}
    lines.extend(
        [
            "`may_depend_on` is empty in every rule below: the allowed direction is a design decision, "
            "not something a scan can observe. Declare it before pasting this into "
            "`.agent/config/architecture.json`, and start with the two or three boundaries you care about.",
            "",
            "```json",
            json.dumps(rules, indent=2),
            "```",
            "",
            "| Module | Import prefix evidence |",
            "|---|---|",
        ]
    )
    for item in report.modules:
        lines.append(f"| `{item.name}` | {item.evidence} |")
    lines.append("")
    return lines


def _entry_points(report: BootstrapReport) -> list[str]:
    if not report.entry_points:
        return []
    listed = ", ".join(f"`{name}`" for name in report.entry_points)
    return [
        "## Existing agent instructions",
        "",
        f"This repository already carries {listed}. Reconcile them with `AGENTS.md` instead of "
        "duplicating guidance, then run `sync-entrypoints` for the ones you want to point here.",
        "",
    ]


def _questions(report: BootstrapReport) -> list[str]:
    lines = [
        "## What no scan can answer",
        "",
        "These stay `TODO` in `.agent/PROJECT.md` until a person or the documentation answers them. "
        "Leave anything unresolved as the literal word `unknown`.",
        "",
    ]
    lines.extend(f"- {item}" for item in report.open_questions)
    lines.append("")
    return lines


def _next_steps(report: BootstrapReport) -> list[str]:
    if report.mode == GREENFIELD:
        steps = [
            "1. Write intent into `.agent/PROJECT.md`: purpose, users, lifecycle `discovery`. "
            "Leave repository paths `unknown` until they exist.",
            "2. Declare the boundaries in `.agent/config/architecture.json` **before** the first feature. "
            "This is the cheapest it will ever be, and it is what keeps the structure from drifting.",
            "3. Create the first spec: `python .agent/workflow.py create-spec <id> --title \"...\" --owner \"...\"`.",
            "4. Fill `.agent/COMMANDS.md` only after the first successful build, from commands you ran.",
            "5. Re-run `bootstrap --force` once code exists; it will then have evidence to work from.",
        ]
    else:
        steps = [
            "1. Run `python .agent/workflow.py adopt` (or `setup`, which includes it).",
            "2. Answer the `TODO` fields `doctor` still reports, or hand the prompt below to an agent.",
            "3. Optional: declare scopes where you will route work differently.",
            "4. Optional: declare architecture modules with `may_depend_on` filled in.",
        ]
    return ["## Next steps", "", *steps, "", "### Prompt for an agent", "", "```text", AGENT_PROMPT, "```", ""]


def render(report: BootstrapReport) -> str:
    sections = (
        _header(report)
        + _ecosystems(report)
        + _commands(report)
        + _facts(report)
        + _scopes(report)
        + _modules(report)
        + _entry_points(report)
        + _questions(report)
        + _next_steps(report)
    )
    return "\n".join(sections).rstrip() + "\n"
